env:
  browser: true
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  no-unused-vars:
    - warn
  no-console:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  # quotes:
  #   - error
  #   - double
  semi:
    - error
    - never
